services:
  postgres:
    image: postgres:16-alpine
    container_name: gumakart-postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gumakart
    volumes:
      - gumakart_pgdata:/var/lib/postgresql/data

volumes:
  gumakart_pgdata:
