import type { ShopTemplateDefinition, ShopTemplateId } from "./types";

export const SHOP_TEMPLATES: ShopTemplateDefinition[] = [
  {
    id: "clean-guma",
    tier: "basic",
    label: "Clean Guma",
    description: "Mobile-first catalog with crisp cards and a friendly checkout flow.",
    mood: "Trusted · everyday · shoppable",
    tags: ["default", "food", "services"],
    previewGradient: "linear-gradient(145deg, #ecfdf5 0%, #059669 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "row",
    hero: "gradient",
    tokens: {
      primary: "#059669",
      accent: "#f59e0b",
      background: "#f4faf7",
      foreground: "#0f172a",
      card: "#ffffff",
      muted: "#64748b",
      border: "#d1fae5",
      mode: "light",
      radius: "1rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "mono-market",
    tier: "basic",
    label: "Mono Market",
    description: "High-contrast black & white layout with sharp type and zero clutter.",
    mood: "Minimal · premium · editorial",
    tags: ["fashion", "prints", "modern"],
    previewGradient: "linear-gradient(160deg, #ffffff 0%, #111827 85%)",
    minPlan: "free",
    layout: "classic",
    header: "minimal",
    card: "row",
    hero: "noise",
    tokens: {
      primary: "#111827",
      accent: "#6b7280",
      background: "#fafafa",
      foreground: "#111827",
      card: "#ffffff",
      muted: "#6b7280",
      border: "#e5e7eb",
      mode: "light",
      radius: "0.375rem",
      displayFont: "system",
    },
  },
  {
    id: "blush-bakery",
    tier: "basic",
    label: "Blush Bakery",
    description: "Soft pastels, rounded shapes, and warm vibes for cakes and sweets.",
    mood: "Cozy · IG-worthy · sweet",
    tags: ["bakery", "pastry", "gifts"],
    previewGradient: "linear-gradient(145deg, #fff1f2 0%, #fecdd3 55%, #fda4af 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "standard",
    card: "row",
    hero: "gradient",
    tokens: {
      primary: "#e11d48",
      accent: "#fb7185",
      background: "#fff7f8",
      foreground: "#4c0519",
      card: "#ffffff",
      muted: "#9f1239",
      border: "#fecdd3",
      mode: "light",
      radius: "1.25rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "neon-bazaar",
    tier: "standard",
    label: "Neon Bazaar",
    description: "Dark mode shop with electric accents — built for TikTok-era discovery.",
    mood: "Gen Z · night market · hype",
    tags: ["streetwear", "snacks", "viral"],
    previewGradient: "linear-gradient(135deg, #0f172a 0%, #7c3aed 50%, #22d3ee 100%)",
    minPlan: "growth",
    layout: "bento",
    header: "floating-glass",
    card: "glass-tile",
    hero: "mesh",
    tokens: {
      primary: "#a855f7",
      accent: "#22d3ee",
      background: "#020617",
      foreground: "#f8fafc",
      card: "rgba(15, 23, 42, 0.72)",
      muted: "#94a3b8",
      border: "rgba(148, 163, 184, 0.25)",
      mode: "dark",
      radius: "1rem",
      displayFont: "mono-accent",
    },
  },
  {
    id: "street-cart",
    tier: "standard",
    label: "Street Cart",
    description: "Sticker collage energy, bold blocks, and loud CTAs like a pop-up stall.",
    mood: "Playful · bold · local",
    tags: ["food cart", "merch", "events"],
    previewGradient: "linear-gradient(145deg, #fef08a 0%, #f97316 45%, #dc2626 100%)",
    minPlan: "growth",
    layout: "hero-stack",
    header: "sticker",
    card: "brutal",
    hero: "gradient",
    tokens: {
      primary: "#ea580c",
      accent: "#facc15",
      background: "#fffbeb",
      foreground: "#1c1917",
      card: "#ffffff",
      muted: "#78716c",
      border: "#1c1917",
      mode: "light",
      radius: "0.5rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "magazine-rack",
    tier: "standard",
    label: "Magazine Rack",
    description: "Editorial grid with big imagery — perfect for lookbooks and curated drops.",
    mood: "Curated · aesthetic · lifestyle",
    tags: ["fashion", "skincare", "gifts"],
    previewGradient: "linear-gradient(160deg, #faf5ff 0%, #ddd6fe 50%, #c4b5fd 100%)",
    minPlan: "growth",
    layout: "editorial",
    header: "split",
    card: "magazine",
    hero: "photo",
    tokens: {
      primary: "#6d28d9",
      accent: "#c084fc",
      background: "#faf5ff",
      foreground: "#2e1065",
      card: "#ffffff",
      muted: "#7c3aed",
      border: "#e9d5ff",
      mode: "light",
      radius: "0.75rem",
      displayFont: "system",
    },
  },
  {
    id: "glass-future",
    tier: "advanced",
    label: "Glass Future",
    description: "Frosted glass layers, soft glow, and floating product tiles — iOS-meets-2030.",
    mood: "Futuristic · premium · sleek",
    tags: ["tech", "beauty", "premium"],
    previewGradient: "linear-gradient(145deg, #dbeafe 0%, #6366f1 50%, #ec4899 100%)",
    minPlan: "pro",
    layout: "immersive",
    header: "floating-glass",
    card: "glass-tile",
    hero: "mesh",
    tokens: {
      primary: "#6366f1",
      accent: "#ec4899",
      background: "linear-gradient(180deg, #eef2ff 0%, #fdf2f8 100%)",
      foreground: "#1e1b4b",
      card: "rgba(255, 255, 255, 0.55)",
      muted: "#6366f1",
      border: "rgba(99, 102, 241, 0.2)",
      mode: "light",
      radius: "1.5rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "y2k-chrome",
    tier: "advanced",
    label: "Y2K Chrome",
    description: "Liquid chrome gradients, bubble UI, and retro-future nostalgia.",
    mood: "Y2K · playful · iconic",
    tags: ["merch", "beauty", "creator"],
    previewGradient: "linear-gradient(135deg, #fbcfe8 0%, #c4b5fd 35%, #67e8f9 70%, #fde68a 100%)",
    minPlan: "pro",
    layout: "bento",
    header: "sticker",
    card: "grid",
    hero: "chrome",
    tokens: {
      primary: "#8b5cf6",
      accent: "#06b6d4",
      background: "#fdf4ff",
      foreground: "#312e81",
      card: "rgba(255,255,255,0.85)",
      muted: "#7c3aed",
      border: "#ddd6fe",
      mode: "light",
      radius: "9999px",
      displayFont: "bricolage",
    },
  },
  {
    id: "holo-grid",
    tier: "advanced",
    label: "Holo Grid",
    description: "Holographic mesh, scanline accents, and floating cards — peak future shop.",
    mood: "Cyber · experimental · flagship",
    tags: ["limited drops", "gaming", "hype"],
    previewGradient: "linear-gradient(135deg, #020617 0%, #0891b2 40%, #d946ef 100%)",
    minPlan: "pro",
    layout: "immersive",
    header: "floating-glass",
    card: "glass-tile",
    hero: "mesh",
    tokens: {
      primary: "#22d3ee",
      accent: "#e879f9",
      background: "#020617",
      foreground: "#ecfeff",
      card: "rgba(2, 6, 23, 0.65)",
      muted: "#67e8f9",
      border: "rgba(34, 211, 238, 0.25)",
      mode: "dark",
      radius: "1rem",
      displayFont: "mono-accent",
    },
  },
];

export const SHOP_TEMPLATE_MAP = Object.fromEntries(
  SHOP_TEMPLATES.map((template) => [template.id, template])
) as Record<ShopTemplateId, ShopTemplateDefinition>;

export function getShopTemplate(id: ShopTemplateId): ShopTemplateDefinition {
  return SHOP_TEMPLATE_MAP[id];
}

/** Template IDs that existed before the rebrand and may still be stored in tenant themeJson. */
const LEGACY_TEMPLATE_IDS: Record<string, ShopTemplateId> = {
  "clean-sari": "clean-guma",
};

export function normalizeShopTemplateId(value: string): string {
  return LEGACY_TEMPLATE_IDS[value] ?? value;
}

export function isShopTemplateId(value: string): value is ShopTemplateId {
  return value in SHOP_TEMPLATE_MAP;
}

export function listShopTemplatesByTier(tier?: ShopTemplateDefinition["tier"]) {
  if (!tier) return SHOP_TEMPLATES;
  return SHOP_TEMPLATES.filter((template) => template.tier === tier);
}

export const TIER_LABELS: Record<ShopTemplateDefinition["tier"], string> = {
  basic: "Basic",
  standard: "Standard",
  advanced: "Advanced",
};

export const TIER_DESCRIPTIONS: Record<ShopTemplateDefinition["tier"], string> = {
  basic: "Clean, fast, and perfect for getting live quickly.",
  standard: "Bold Gen Z layouts with more personality and motion-ready structure.",
  advanced: "Futuristic flagship designs for brands that want to stand out.",
};
