export { db, getDb, closeDb, type Database } from "./client";
export { getDatabaseUrl, isNeonDatabase } from "./env";
export {
  getTenantStorefrontBySlug,
  getTenantStorefrontPreviewBySlug,
  getPendingTenantBySlug,
  type StorefrontTenantRecord,
  type PendingTenantRecord,
} from "./queries/storefront";
export {
  getTenantDashboard,
  activateTenantShop,
  tryAutoActivateTenant,
  type TenantDashboardData,
  type SetupStep,
} from "./queries/tenant-dashboard";
export {
  getTenantStorefrontSettings,
  updateTenantStorefront,
  type TenantStorefrontSettings,
  type UpdateTenantStorefrontInput,
} from "./queries/tenant-storefront";
export {
  getTenantSettings,
  updateTenantSettings,
  type TenantSettingsJson,
  type TenantSettingsRecord,
  type UpdateTenantSettingsInput,
} from "./queries/tenant-settings";
export {
  listProductsForTenant,
  getProductForTenant,
  createProductForTenant,
  updateProductForTenant,
  deleteProductForTenant,
  isProductSlugAvailable,
  slugFromProductTitle,
  normalizeProductSlug,
  type ProductListItem,
  type CreateProductInput,
  type UpdateProductInput,
  type DeleteProductResult,
} from "./queries/products";
export {
  createCategoryForTenant,
  deleteCategoryForTenant,
  isCategorySlugAvailable,
  listCategoriesForTenant,
  slugFromCategoryName,
  type CategoryListItem,
} from "./queries/categories";
export {
  getRawAiUsageCounts,
  recordAiUsage,
  getTenantOwnerContact,
  type RawAiUsageCounts,
} from "./queries/ai-usage";
export {
  createOrderForTenant,
  getOrderForTracking,
  getOrderPaymentForRefund,
  listOrdersForTenant,
  markOrderPaidByIntent,
  markOrderRefunded,
  markPaymentFailedByIntent,
  recordPaymentIntent,
  updateOrderStatusForTenant,
  OrderError,
  ORDER_STATUS_TRANSITIONS,
  type CreateOrderInput,
  type CreatedOrder,
  type MarkOrderPaidResult,
  type OrderRefundInfo,
  type OrderStatus,
  type OrderTrackingData,
  type OrderTrackingDelivery,
  type TenantOrderListItem,
} from "./queries/orders";
export {
  persistDomainEvent,
  listDomainEventsForTenant,
  type DomainEventRow,
} from "./queries/domain-events";
export {
  PLAN_PRICES_PHP,
  PLAN_PERIOD_DAYS,
  createPlanPayment,
  markPlanPaymentPaidByIntent,
  type CreatePlanPaymentInput,
  type MarkPlanPaymentPaidResult,
} from "./queries/plan-billing";
export {
  SELLER_PLANS,
  PLATFORM_PLANS as PLAN_CATALOG,
  getSellerPlan,
  normalizePlanId,
  planPriceMonthly,
  type PlanDefinition,
  type SubscriptionPlanId,
} from "./plans";
export {
  getLaunchTenantState,
  updateStoreDna,
  saveThemeDraft,
  publishThemeDraft,
  resolvePublishedThemeJson,
  needsGumaLaunch,
  resolveSellerHomePath,
  type LaunchTenantState,
  type ThemeJson,
  type StoreDnaJson,
} from "./queries/launch";
export {
  createChangeRequest,
  submitChangeRequest,
  approveChangeRequest,
  rejectChangeRequest,
  getChangeRequest,
  listChangeRequestsForTenant,
  writeTenantAudit,
  listTenantAudit,
  publishThemeChangeRequest,
  publishCatalogChangeRequest,
  publishPricingChangeRequest,
  publishSeoChangeRequest,
  rollbackSeoChangeRequest,
  publishCheckoutChangeRequest,
  rollbackCheckoutChangeRequest,
  publishShippingChangeRequest,
  rollbackShippingChangeRequest,
  markChangeRequestPublished,
  publishStorefrontWithApproval,
  rollbackThemeChangeRequest,
  type ChangeRequestRow,
  type ChangeRequestDomain,
  type ChangeRequestStatus,
  type ActorType,
  type CatalogListingProposal,
  type PricingProposal,
} from "./queries/change-requests";
export {
  getTenantSeoState,
  saveTenantSeoDraft,
  publishTenantSeo,
  buildDefaultSeo,
  normalizeSeoJson,
  EMPTY_SEO,
  type TenantSeoJson,
  type TenantSeoState,
} from "./queries/seo";
export {
  getTenantCheckoutState,
  saveTenantCheckoutDraft,
  publishTenantCheckout,
  getPublishedCheckoutForSlug,
  upsertCheckoutSession,
  markCheckoutSessionConverted,
  abandonStaleCheckoutSessions,
  normalizeCheckoutJson,
  checkoutFromLegacySettings,
  computeCheckoutTotals,
  findActiveCoupon,
  isPaymentMethodEnabled,
  EMPTY_CHECKOUT,
  type TenantCheckoutJson,
  type TenantCheckoutState,
} from "./queries/checkout";
export type { CheckoutTotals } from "./types/tenant-checkout";
export {
  getTenantShippingState,
  saveTenantShippingDraft,
  publishTenantShipping,
  getPublishedShippingForSlug,
  normalizeShippingJson,
  shippingFromLegacyDelivery,
  legacyDeliveryFromShipping,
  resolveShippingFee,
  isPickupEnabled,
  EMPTY_SHIPPING,
  type TenantShippingJson,
  type TenantShippingState,
} from "./queries/shipping";
export {
  savePushSubscription,
  deletePushSubscription,
  deletePushSubscriptions,
  listPushSubscriptionsForTenant,
  type SavePushSubscriptionInput,
  type TenantPushSubscription,
} from "./queries/push-subscriptions";
export {
  recordDeliveryQuote,
  createDeliveryBooking,
  updateDeliveryByProviderOrderId,
  advanceOrderStatusFromDelivery,
  getDeliveryForOrder,
  getOrderForDeliveryBooking,
  type RecordDeliveryQuoteInput,
  type CreateDeliveryBookingInput,
  type DeliveryStatusPatch,
  type OrderDeliveryInfo,
  type OrderForDeliveryBooking,
} from "./queries/deliveries";
export {
  getOrderInsightsLast7d,
  getProductById,
  pickFeaturedProductId,
  type OrderInsights7d,
} from "./queries/order-insights";
export {
  listContentQueue,
  createContentQueueItem,
  updateContentQueueStatus,
  startAgentRun,
  finishAgentRun,
  listRecentAgentRuns,
  listActiveTenantsForAgents,
  saveShopChatMessage,
  getTenantIdBySlug,
  resolveAgentSettings,
  resolveShopAssistantSettings,
  DEFAULT_AGENT_SETTINGS,
  DEFAULT_SHOP_ASSISTANT,
  type ContentQueueItem,
  type AgentSettings,
  type ShopAssistantSettings,
} from "./queries/agents";
export {
  PLATFORM_PLANS,
  TENANT_STATUSES,
  USER_STATUSES,
  getPlanById,
  planPrice,
  getPlatformStats,
  getSignupSeries,
  getRevenueSeries,
  listTenants,
  getTenantDetail,
  setTenantStatus,
  setTenantPlan,
  listUsers,
  getUserRoleCounts,
  setUserStatus,
  setUserRole,
  listModerationQueue,
  getModerationCounts,
  moderateContentItem,
  listPlatformOrders,
  writeAudit,
  listAuditLog,
  type PlatformPlan,
  type TenantStatus,
  type UserStatus,
  type PlatformStats,
  type DailyPoint,
  type TenantListItem,
  type ListTenantsFilters,
  type TenantDetail,
  type UserListItem,
  type ListUsersFilters,
  type ModerationItem,
  type ListModerationFilters,
  type ModerateInput,
  type PlatformOrderItem,
  type AuditEntry,
  type AuditLogItem,
} from "./queries/platform";
export {
  getWalletSummary,
  listWalletLedger,
  listTenantPayouts,
  requestTenantPayout,
  runWalletSettlement,
  processQueuedPayouts,
  resolveWalletSettings,
  creditSaleForOrder,
  WalletError,
  type TenantWalletSummary,
  type WalletLedgerItem,
  type TenantPayoutItem,
  type TenantWalletSettings,
} from "./queries/wallet";
export {
  PLATFORM_FEE_PERCENT,
  PLATFORM_FEE_FIXED_PHP,
  computePlatformFeeCentavos,
  computeSellerNetCentavos,
  walletClearanceHours,
  minAutoPayoutCentavos,
} from "./wallet-fees";
export {
  getLatestKycSession,
  getActiveKycSession,
  getOrCreateActiveKycSession,
  getKycSessionByToken,
  getKycSessionById,
  updateKycSession,
  upsertKycDocument,
  submitKycSession,
  validateKycSubmission,
  getKycDocumentStorageKey,
  getKycDocumentByToken,
  KycValidationError,
  type KycSessionRecord,
  type KycDocumentRecord,
  type KycStatus,
  type KycIdPath,
  type KycDocType,
} from "./queries/kyc";
export * from "./schema/index";
