export { db, getDb, closeDb, type Database } from "./client";
export { getDatabaseUrl, isNeonDatabase } from "./env";
export {
  getTenantStorefrontBySlug,
  getPendingTenantBySlug,
  type StorefrontTenantRecord,
  type PendingTenantRecord,
} from "./queries/storefront";
export {
  getTenantDashboard,
  activateTenantShop,
  type TenantDashboardData,
  type SetupStep,
} from "./queries/tenant-dashboard";
export {
  getTenantStorefrontSettings,
  updateTenantStorefront,
  type TenantStorefrontSettings,
  type UpdateTenantStorefrontInput,
} from "./queries/tenant-storefront";
export {
  getTenantSettings,
  updateTenantSettings,
  type TenantSettingsJson,
  type TenantSettingsRecord,
  type UpdateTenantSettingsInput,
} from "./queries/tenant-settings";
export {
  listProductsForTenant,
  createProductForTenant,
  updateProductForTenant,
  deleteProductForTenant,
  isProductSlugAvailable,
  slugFromProductTitle,
  normalizeProductSlug,
  type ProductListItem,
  type CreateProductInput,
  type UpdateProductInput,
  type DeleteProductResult,
} from "./queries/products";
export {
  createCategoryForTenant,
  deleteCategoryForTenant,
  isCategorySlugAvailable,
  listCategoriesForTenant,
  slugFromCategoryName,
  type CategoryListItem,
} from "./queries/categories";
export {
  getRawAiUsageCounts,
  recordAiUsage,
  getTenantOwnerContact,
  type RawAiUsageCounts,
} from "./queries/ai-usage";
export {
  createOrderForTenant,
  getOrderForTracking,
  getOrderPaymentForRefund,
  listOrdersForTenant,
  markOrderPaidByIntent,
  markOrderRefunded,
  markPaymentFailedByIntent,
  recordPaymentIntent,
  updateOrderStatusForTenant,
  OrderError,
  ORDER_STATUS_TRANSITIONS,
  type CreateOrderInput,
  type CreatedOrder,
  type MarkOrderPaidResult,
  type OrderRefundInfo,
  type OrderStatus,
  type OrderTrackingData,
  type OrderTrackingDelivery,
  type TenantOrderListItem,
} from "./queries/orders";
export {
  PLAN_PRICES_PHP,
  PLAN_PERIOD_DAYS,
  createPlanPayment,
  markPlanPaymentPaidByIntent,
  type CreatePlanPaymentInput,
  type MarkPlanPaymentPaidResult,
} from "./queries/plan-billing";
export {
  savePushSubscription,
  deletePushSubscription,
  deletePushSubscriptions,
  listPushSubscriptionsForTenant,
  type SavePushSubscriptionInput,
  type TenantPushSubscription,
} from "./queries/push-subscriptions";
export {
  recordDeliveryQuote,
  createDeliveryBooking,
  updateDeliveryByProviderOrderId,
  advanceOrderStatusFromDelivery,
  getDeliveryForOrder,
  getOrderForDeliveryBooking,
  type RecordDeliveryQuoteInput,
  type CreateDeliveryBookingInput,
  type DeliveryStatusPatch,
  type OrderDeliveryInfo,
  type OrderForDeliveryBooking,
} from "./queries/deliveries";
export {
  getOrderInsightsLast7d,
  getProductById,
  pickFeaturedProductId,
  type OrderInsights7d,
} from "./queries/order-insights";
export {
  listContentQueue,
  createContentQueueItem,
  updateContentQueueStatus,
  startAgentRun,
  finishAgentRun,
  listRecentAgentRuns,
  listActiveTenantsForAgents,
  saveShopChatMessage,
  getTenantIdBySlug,
  resolveAgentSettings,
  resolveShopAssistantSettings,
  DEFAULT_AGENT_SETTINGS,
  DEFAULT_SHOP_ASSISTANT,
  type ContentQueueItem,
  type AgentSettings,
  type ShopAssistantSettings,
} from "./queries/agents";
export {
  PLATFORM_PLANS,
  TENANT_STATUSES,
  USER_STATUSES,
  getPlanById,
  planPrice,
  getPlatformStats,
  getSignupSeries,
  getRevenueSeries,
  listTenants,
  getTenantDetail,
  setTenantStatus,
  setTenantPlan,
  listUsers,
  getUserRoleCounts,
  setUserStatus,
  setUserRole,
  listModerationQueue,
  getModerationCounts,
  moderateContentItem,
  listPlatformOrders,
  writeAudit,
  listAuditLog,
  type PlatformPlan,
  type TenantStatus,
  type UserStatus,
  type PlatformStats,
  type DailyPoint,
  type TenantListItem,
  type ListTenantsFilters,
  type TenantDetail,
  type UserListItem,
  type ListUsersFilters,
  type ModerationItem,
  type ListModerationFilters,
  type ModerateInput,
  type PlatformOrderItem,
  type AuditEntry,
  type AuditLogItem,
} from "./queries/platform";
export * from "./schema/index";
